site_name: 人工智能面试集合
site_author: Buffalo
site_url:  https://github.com/buffaloboyhlh/interviews
repo_url: https://github.com/buffaloboyhlh/interviews
theme:
  name: material
  primary: teal
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: teal # 上方的
      accent: amber # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - math
    - diagrams
  language: zh

plugins:
  - search
#  - macros

extra_css:
  - styles/extra.css
  - styles/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - styles/javascripts/katex.js

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 2-3

nav:
  - 机器学习: machine/interview.md
  - 深度学习: deeplearning/interview.md
  - 从零开始学NLP:
      - 第 1 章：文本表示与词向量: nlp/chart01.md
      - 第 2 章：RNN/LSTM 序列模型: nlp/chart02.md
      - 第 3 章：Transformer 与 Self-Attention: nlp/chart03.md
      - 第 4 章：BERT / GPT 原理与微调: nlp/chart04.md
      - 第 5 章：NLP 实战与部署: nlp/chart05.md
      - nltk库: nlp/nltk.md
      - peft库: nlp/peft.md

  - 大模型应用开发:
      - LangChain核心组件:
          - 智能体（Agents）: llmapps/langchain/core-components/agents.md
          - 模型（Models）: llmapps/langchain/core-components/models.md
          - 消息（Messages）: llmapps/langchain/core-components/messages.md
          - 工具（Tools）: llmapps/langchain/core-components/tools.md
          - 短期记忆（Short-term memory）: llmapps/langchain/core-components/short-term memory.md
          - 流（Streaming）: llmapps/langchain/core-components/streaming.md
          - 中间件（Middleware）: llmapps/langchain/core-components/middleware.md
          - 结构化输出（Structured output）: llmapps/langchain/core-components/structured-output.md
      - LangChain进阶用法:
          - Guardrails: llmapps/langchain/advanced-usage/Guardrails.md
          - Runtime: llmapps/langchain/advanced-usage/Runtime.md
          - Context-engineering: llmapps/langchain/advanced-usage/context-engineering.md
          - Model Context Protocol: llmapps/langchain/advanced-usage/MCP.md
          - Human-in-the-loop: llmapps/langchain/advanced-usage/Human-in-the-loop.md
          - Multi-agent: llmapps/langchain/advanced-usage/Multi-agent.md
          - Retrieval: llmapps/langchain/advanced-usage/Retrieval.md
          - Long-term memory: llmapps/langchain/advanced-usage/Long-term memory.md

      - LangChain应用开发:
          - 相似搜索: llmapps/apps/langchain/semantic search.md
          - RAG agent: llmapps/apps/langchain/RAG agent.md
          - 人工审核: llmapps/apps/langchain/humain_middleware.md

      - LangGraph:
          - 概述: llmapps/langgraph/overview.md
          - 快速入门: llmapps/langgraph/quickstart.md
          - Local server: llmapps/langgraph/Local server.md
          - Thinking in LangGraph: llmapps/langgraph/thinking in Langgraph.md
          - Workflows+agents: llmapps/langgraph/workflows+agents.md
          - Persistence: llmapps/langgraph/persistence.md
          - Durable execution: llmapps/langgraph/durable execution.md
          - Streaming: llmapps/langgraph/streaming.md
          - Interrupts: llmapps/langgraph/interrupts.md
          - Time travel: llmapps/langgraph/time travel.md
          - Memory: llmapps/langgraph/memory.md
          - Subgraphs: llmapps/langgraph/Subgraphs.md
          - Application structure: llmapps/langgraph/application structure.md
          - Graph API:
              - Graph API: llmapps/langgraph/graph api overview.md
              - Use the graph API: llmapps/langgraph/use the graph api.md
  - 向量数据库:
      - Chroma:  Vector Stores/Chroma/tutorial.md
      - Milvus: Vector Stores/Milvus/tutorial.md
      - FAISS: Vector Stores/FAISS/tutorial.md
  - 大模型微调和部署:
      - 大模型部署:
          - Streamlit: llm/deploy/Streamlit/tutorial.md
          - Gradio: llm/deploy/Gradio/tutorial.md
      -  大模型微调:
           - Transformers:
               - 快速入门: llm/tunning/transformers/quick start.md
           - PEFT:
               - 快速入门: llm/tunning/peft/quick start.md
               - 中文PEFT微调实战: llm/tunning/peft/chinese peft.md
      - 大模型推理:
          - vLLM:
              - 快速入门: llm/inference/vLLM/quick start.md
  - 其他:
    - WSL: others\wsl.md





